#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
Created on Sat Jan 28 21:50:54 2023

@author: axelcasas
"""

"""sleep_data.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1lnmrum-t1UUiwDucgTJTTBGZ_Ovk0O54

"""

import pandas as pd
import datetime

'''
IMPORT DATA FROM GOOGLE SPREADSHEET
Here I used google colab to analyze and show all the data.

If you're going to use colab as well, one way to import the data is by using the link of
your google spreadsheet: 
https://docs.google.com/spreadsheets/d/1P_TFYieDBRvClHK0qjIeQSh0_cIb481WrLSbalxw-6w/edit?usp=sharing

Note that in this way your link needs to be available for everyone. When you share it make sure is available
to anyone with the link.

'''

sheet_id = '1P_TFYieDBRvClHK0qjIeQSh0_cIb481WrLSbalxw-6w'

psqi = pd.read_csv(f'https://docs.google.com/spreadsheets/d/{sheet_id}/export?format=csv')
# we drop columns that we'll not use
psqi = psqi.drop(columns = ['Timestamp','¿Desea participar en la investigación?'])


'''
RENAME COLUMNS
Note that the questions are in Spanish.
'''

psqi = psqi.rename(columns = {
    'Edad':'edad',
    'Género Autopercibido':'genero',
    'Durante el último mes: ¿Cuál ha sido, normalmente, su hora para acostarse? Responda la hora habitual para acostarse (en sistema de 24 horas):':'psqi_hora_habitual_acostarse',
    '¿Cuánto tiempo ha tardado en dormirse, normalmente, en las noches del último mes? Responda el tiempo en minutos:':'psqi_tiempo_para_dormirse',
    '¿A qué hora se ha levantado habitualmente por la mañana durante el último mes? Responda la hora habitual de levantarse:':'psqi_hora_levantarse',
    '¿Cuántas horas calcula que habrá dormido verdaderamente cada noche durante el último mes? (El tiempo puede ser diferente al que usted permanezca en la cama)':'psqi_horas_dormir_subjetivo',
    'Durante el último mes, cuántas veces ha tenido usted problemas para dormir a causa de:':'psqi_problemas_conciliar_sueno_primera_hora',
    'Durante el último mes, cuántas veces ha tenido usted problemas para dormir a causa de:.1':'psqi_problemas_despertarse_noche',
    'Durante el último mes, cuántas veces ha tenido usted problemas para dormir a causa de:.2':'psqi_problemas_bano',
    'Durante el último mes, cuántas veces ha tenido usted problemas para dormir a causa de:.3':'psqi_problemas_respirar_mal',
    'Durante el último mes, cuántas veces ha tenido usted problemas para dormir a causa de:.4': 'psqi_problemas_toser_roncar',
    'Durante el último mes, cuántas veces ha tenido usted problemas para dormir a causa de:.5': 'psqi_problemas_sentir_frio',
    'Durante el último mes, cuántas veces ha tenido usted problemas para dormir a causa de:.6': 'psqi_problemas_sentir_calor',
    'Durante el último mes, cuántas veces ha tenido usted problemas para dormir a causa de:.7': 'psqi_problemas_pesadillas',
    'Durante el último mes, cuántas veces ha tenido usted problemas para dormir a causa de:.8':'psqi_problemas_dolores',
    'Otras razones (por favor, descríbalas a continuación)': 'psqi_problemas_otros',
    '6- Durante el último mes, ¿cómo valoraría, en conjunto, la calidad de su sueño?':'psqi_calidad_sueno_subjetiva',
    '7) Durante el último mes, ¿cuántas veces ha tomado medicinas (por su cuenta o recetadas por el médico) para dormir?':'psqi_consumo_medicinas_para_dormir',
    '8) Durante el último mes, ¿cuántas veces ha sentido somnolencia mientras conducía, comía, o desarrollaba alguna otra actividad?':'psqi_somnolencia',
    '9) Durante el último mes, ¿ha representado para usted mucho problema el tener ánimos/energías para realizar alguna de las actividades detalladas en la pregunta anterior?':'psqi_animos',
    '10) ¿Duerme usted sólo o acompañado?':'psqi_companero_dormir',
    'Si usted tiene pareja, o compañero/a de habitación, pregúntele si durante el último mes usted ha tenido:':'psqi_companero_ronquidos',
    'Si usted tiene pareja, o compañero/a de habitación, pregúntele si durante el último mes usted ha tenido:.1': 'psqi_companero_pausas_entre_respiraciones',
    'Si usted tiene pareja, o compañero/a de habitación, pregúntele si durante el último mes usted ha tenido:.2':'psqi_companero_sacudidas_piernas',
    'Si usted tiene pareja, o compañero/a de habitación, pregúntele si durante el último mes usted ha tenido:.3':'psqi_companero_episodios_desorientacion',
    'E) Otros inconvenientes mientras usted duerme (por favor, descríbalos a continuación)':'psqi_companero_otros',
    'Si querés conocer tu calidad de sueño dejanos tu mail 😴':'mail_feedback'
})

'''
CLEANING
'''

clean_psqi = psqi.replace({'Ninguna vez en el último mes':0,
                           'Ninguna en el último mes':0,
        'Menos de una vez a la semana':1,
        'Una o dos veces a la semana':2,
        'Tres o más veces a la semana':3,

        'Ningún problema':0,
        'Sólo un leve problema':1,
        'Un problema':2,
        'Un grave problema':3,
        
        'Bastante buena':0,
        'Buena':1,
        'Mala':2,
        'Bastante mala':3
})
psqi = clean_psqi

'''
Now we need to convert time data to float using datetime module
'''
psqi['psqi_hora_habitual_acostarse'] = psqi['psqi_hora_habitual_acostarse'].apply(pd.to_datetime,  errors='coerce')
psqi['psqi_hora_levantarse'] = psqi['psqi_hora_levantarse'].apply(pd.to_datetime, errors='coerce')

psqi['psqi_hora_habitual_acostarse'] = psqi['psqi_hora_habitual_acostarse'].dt.strftime("%H.%M").astype(float)
psqi['psqi_hora_levantarse'] = psqi['psqi_hora_levantarse'].dt.strftime("%H.%M").astype(float)

psqi['psqi_horas_dormir_subjetivo'] = psqi['psqi_horas_dormir_subjetivo'].apply(pd.to_datetime, errors='coerce')
psqi['psqi_horas_dormir_subjetivo'] = psqi['psqi_horas_dormir_subjetivo'].dt.strftime("%H.%M").astype(float)

"""
SCORING
For a detailed PSQI scoring see https://drive.google.com/file/d/10QdC6X83BbI0X_12ocbtY4pSa3jeSaip/view
"""

"""## COMP 1: Subjective Sleep quality"""

psqi_comp1 = psqi['psqi_calidad_sueno_subjetiva']
psqi['comp1'] = psqi_comp1
psqi['comp1'].value_counts()

"""## COMP 2: Sleep Latency"""

comp2a = []

for row in psqi['psqi_tiempo_para_dormirse']:
  if row <= 15:
    comp2a.append(0)
  elif row >= 16 and row <= 30:
    comp2a.append(1)
  elif row >= 31 and row <= 60:
    comp2a.append(2)
  elif row > 60:
    comp2a.append(3)


psqi['comp2a'] = comp2a

comp2b = psqi['psqi_problemas_conciliar_sueno_primera_hora']

comp2_sum = comp2a + comp2b

psqi['comp2_sum'] = comp2_sum

comp2 = []

for row in psqi['comp2_sum']:
  if row == 0:
    comp2.append(0)
  elif row >= 1 and row <= 2:
    comp2.append(1)
  elif row >= 3 and row <= 4:
    comp2.append(2)
  elif row >= 5 and row <= 6:
    comp2.append(3)

psqi['comp2'] = comp2

"""## COMP 3: Sleep Duration"""

comp3 = []

for row in psqi['psqi_horas_dormir_subjetivo']:
  if row >7:
    comp3.append(0)
  elif row >= 6 and row <=7:
    comp3.append(1)
  elif row >=5 and row <= 6:
    comp3.append(2)
  elif row <5:
    comp3.append(3)

psqi['comp3'] = comp3

"""## COMP 4: Habitual Sleep Efficiency"""

comp4a = psqi['psqi_horas_dormir_subjetivo']
comp4b = psqi['psqi_hora_habitual_acostarse'] + psqi['psqi_hora_levantarse']

comp4 = (comp4a/comp4b)*100
psqi['comp4_analysis'] = comp4
psqi['comp4_analysis'] = psqi['comp4_analysis'].round()

comp4 = []

for row in psqi['comp4_analysis']:
  if row >= 85:
    comp4.append(0)
  elif row >= 75 and row <= 84:
    comp4.append(1)
  elif row >= 65 and row <= 74:
    comp4.append(2)
  elif row < 65:
    comp4.append(3)

psqi['comp4'] = comp4

"""## COMP 5: Sleep Disturbances"""

comp5 = psqi.filter(regex='psqi_problemas')
comp5 = comp5.drop(columns = ['psqi_problemas_conciliar_sueno_primera_hora'])
comp5 = comp5.sum(axis=1)

psqi['comp5_analysis'] = comp5

comp5 = []

for row in psqi['comp5_analysis']:
  if row == 0:
    comp5.append(0)
  elif row >= 1 and row <=9:
    comp5.append(1)
  elif row >= 10 and row <=18:
    comp5.append(2)
  elif row >=19 and row <=27:
    comp5.append(3)

psqi['comp5'] = comp5

"""## COMP 6: Use of Sleep Medication"""

comp6 = psqi['psqi_consumo_medicinas_para_dormir']
psqi['comp6'] = comp6

"""## COMP 7: Daytime Dysfunction"""

comp7 = psqi['psqi_animos'] + psqi['psqi_somnolencia']
psqi['comp7'] = comp7

"""
FINAL SCORE
"""

# filter the columns and delete the ones you don't need
components = psqi.filter(psqi.columns[24:])
components = components.drop(columns = ['comp2a','comp2_sum','comp4_analysis','comp5_analysis','psqi_companero_otros','psqi_companero_episodios_desorientacion','mail_feedback'])

# sum all the components
final_score = components.sum(axis=1)
psqi['SCORE'] = final_score

psqi['SCORE']